server:
  port: 8082

spring:
  application:
    name: inventory-service
  data:
    mongodb:
      uri: mongodb://root:rootpass@localhost:27017/inventory?authSource=admin
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: inventory-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

kafka:
  bootstrap-servers: localhost:9092

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
tracing:
  sampling:
    probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
